#!/bin/bash

# Commit Automation - Pre-Commit Hook  
# Automatically updates PROJECT.md, builds project, and stages artifacts

set -e

AUTOMATION_DIR=".commit-automation"
LOG_FILE="${AUTOMATION_DIR}/commit.log"

# Create automation directory if missing
mkdir -p "${AUTOMATION_DIR}"

# Logging function
log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $1" | tee -a "${LOG_FILE}"
}

log "🔧 Commit Automation System activated"

# Load project configuration
if [ ! -f "${AUTOMATION_DIR}/project-config.json" ]; then
    log "❌ Project configuration missing. Run install.sh first."
    exit 1
fi

PROJECT_NAME=$(jq -r '.project_name' "${AUTOMATION_DIR}/project-config.json")
PROJECT_TYPE=$(jq -r '.project_type' "${AUTOMATION_DIR}/project-config.json")
GITHUB_URL=$(jq -r '.github_url' "${AUTOMATION_DIR}/project-config.json")

log "📁 Project: ${PROJECT_NAME} (${PROJECT_TYPE})"

# Check if PROJECT.md exists
if [ ! -f "PROJECT.md" ]; then
    log "❌ PROJECT.md not found. Creating from template..."
    
    # Create basic PROJECT.md
    cat > "PROJECT.md" << EOF
# PROJECT.md - Single Source of Truth

## Project Info
- **Name**: ${PROJECT_NAME}
- **Version**: v1.0.0
- **Status**: development
- **Platforms**: unknown
- **Description**: Project description needs to be updated

## Repository
- **Main Branch**: main
- **GitHub**: ${GITHUB_URL}

## Backlog
- **TODO**: Update PROJECT.md with complete information
- **TODO**: Add proper project description and technical details

---
*Last Updated: $(date -u +%Y-%m-%dT%H:%M:%SZ)*
*Auto-generated by commit-automation*
EOF
    
    log "   ✅ Basic PROJECT.md created"
fi

# Parse current version from PROJECT.md
CURRENT_VERSION=$(grep -E "^\s*-\s*\*\*Version\*\*:" PROJECT.md | sed -E 's/.*v([0-9]+\.[0-9]+\.[0-9]+).*/\1/' || echo "1.0.0")
log "📋 Current version: v${CURRENT_VERSION}"

# Determine version increment based on commit message
COMMIT_MSG_FILE=".git/COMMIT_EDITMSG"
COMMIT_TYPE="patch"  # default

if [ -f "${COMMIT_MSG_FILE}" ]; then
    COMMIT_MSG=$(cat "${COMMIT_MSG_FILE}")
    
    if [[ "${COMMIT_MSG}" =~ ^feat(\(.+\))?!?: ]] || [[ "${COMMIT_MSG}" =~ BREAKING.CHANGE ]]; then
        if [[ "${COMMIT_MSG}" =~ ! ]] || [[ "${COMMIT_MSG}" =~ BREAKING.CHANGE ]]; then
            COMMIT_TYPE="major"
        else
            COMMIT_TYPE="minor"
        fi
    elif [[ "${COMMIT_MSG}" =~ ^fix(\(.+\))?: ]]; then
        COMMIT_TYPE="patch"
    elif [[ "${COMMIT_MSG}" =~ ^(docs|style|refactor|test|chore)(\(.+\))?: ]]; then
        COMMIT_TYPE="patch"
    fi
fi

# Calculate new version
IFS='.' read -r major minor patch <<< "${CURRENT_VERSION}"

case "${COMMIT_TYPE}" in
    "major")
        major=$((major + 1))
        minor=0
        patch=0
        ;;
    "minor")
        minor=$((minor + 1))
        patch=0
        ;;
    "patch")
        patch=$((patch + 1))
        ;;
esac

NEW_VERSION="${major}.${minor}.${patch}"
log "🔄 Version increment (${COMMIT_TYPE}): v${CURRENT_VERSION} → v${NEW_VERSION}"

# Update PROJECT.md with new version and timestamp
TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)

# Update version line
sed -i.bak "s/- \*\*Version\*\*:.*/- **Version**: v${NEW_VERSION}/" PROJECT.md

# Update timestamp line
sed -i.bak "s/\*Last Updated:.*/\*Last Updated: ${TIMESTAMP}\*/" PROJECT.md

# Clean backup
rm -f PROJECT.md.bak

log "   ✅ PROJECT.md updated with v${NEW_VERSION}"

# Build project based on type
BUILD_SUCCESS=false
ARTIFACTS=()

case "${PROJECT_TYPE}" in
    "flutter")
        log "📱 Building Flutter project..."
        
        # Check if we should build APK
        if [ -f "android/app/build.gradle" ]; then
            log "   Building APK..."
            if flutter build apk --release > "${AUTOMATION_DIR}/build.log" 2>&1; then
                APK_PATH="build/app/outputs/flutter-apk/app-release.apk"
                if [ -f "${APK_PATH}" ]; then
                    mkdir -p "releases"
                    RELEASE_APK="releases/${PROJECT_NAME,,}-v${NEW_VERSION}.apk"
                    cp "${APK_PATH}" "${RELEASE_APK}"
                    ARTIFACTS+=("${RELEASE_APK}")
                    log "   ✅ APK built: ${RELEASE_APK}"
                    BUILD_SUCCESS=true
                fi
            else
                log "   ⚠️  APK build failed, check ${AUTOMATION_DIR}/build.log"
            fi
        fi
        
        # Check if we should build web
        if [ -f "web/index.html" ]; then
            log "   Building Web..."
            if flutter build web --release > "${AUTOMATION_DIR}/web-build.log" 2>&1; then
                mkdir -p "releases"
                RELEASE_WEB="releases/${PROJECT_NAME,,}-web-v${NEW_VERSION}.zip"
                (cd build/web && zip -r "../../${RELEASE_WEB}" . > /dev/null)
                ARTIFACTS+=("${RELEASE_WEB}")
                log "   ✅ Web built: ${RELEASE_WEB}"
                BUILD_SUCCESS=true
            fi
        fi
        ;;
        
    "nodejs")
        log "🌐 Building Node.js project..."
        
        if [ -f "package.json" ] && grep -q '"build"' package.json; then
            log "   Running npm build..."
            if npm run build > "${AUTOMATION_DIR}/build.log" 2>&1; then
                if [ -d "build" ] || [ -d "dist" ]; then
                    mkdir -p "releases"
                    BUILD_DIR="build"
                    [ -d "dist" ] && BUILD_DIR="dist"
                    
                    RELEASE_WEB="releases/${PROJECT_NAME,,}-web-v${NEW_VERSION}.zip"
                    (cd "${BUILD_DIR}" && zip -r "../${RELEASE_WEB}" . > /dev/null)
                    ARTIFACTS+=("${RELEASE_WEB}")
                    log "   ✅ Web build packaged: ${RELEASE_WEB}"
                    BUILD_SUCCESS=true
                fi
            else
                log "   ⚠️  Build failed, check ${AUTOMATION_DIR}/build.log"
            fi
        fi
        ;;
        
    "static")
        log "📄 Static site detected..."
        
        # For static sites, just package the current files
        mkdir -p "releases"
        RELEASE_STATIC="releases/${PROJECT_NAME,,}-static-v${NEW_VERSION}.zip"
        
        # Package main files (excluding git, node_modules, etc.)
        zip -r "${RELEASE_STATIC}" . \
            -x "*.git*" "node_modules/*" ".commit-skin/*" "releases/*" \
            > /dev/null
            
        ARTIFACTS+=("${RELEASE_STATIC}")
        log "   ✅ Static site packaged: ${RELEASE_STATIC}"
        BUILD_SUCCESS=true
        ;;
        
    *)
        log "❓ Unknown project type, skipping build"
        BUILD_SUCCESS=true  # Don't fail for unknown types
        ;;
esac

# Stage PROJECT.md changes
git add PROJECT.md
log "   ✅ PROJECT.md staged"

# Stage any built artifacts
for artifact in "${ARTIFACTS[@]}"; do
    git add "${artifact}"
    log "   ✅ Staged artifact: ${artifact}"
done

# Create a build summary comment for the commit message  
if [ ${#ARTIFACTS[@]} -gt 0 ]; then
    SUMMARY_FILE="${AUTOMATION_DIR}/commit-summary.txt"
    
    cat > "${SUMMARY_FILE}" << EOF

Auto-generated by commit-automation:
- Updated PROJECT.md: v${CURRENT_VERSION} → v${NEW_VERSION}
- Built ${#ARTIFACTS[@]} artifact(s): ${ARTIFACTS[*]}
- Ready for deployment by Ciccio
EOF
    
    # Append to commit message if it exists
    if [ -f "${COMMIT_MSG_FILE}" ]; then
        cat "${SUMMARY_FILE}" >> "${COMMIT_MSG_FILE}"
    fi
    
    log "   ✅ Commit message enhanced with build summary"
fi

# Final status
if [ "${BUILD_SUCCESS}" = true ]; then
    log "🎉 Commit preparation complete!"
    log "   Version: v${NEW_VERSION}"
    log "   Artifacts: ${#ARTIFACTS[@]}"
    log "   Ready for push to GitHub"
else
    log "⚠️  Commit prepared but build had issues"
    log "   Check logs in ${AUTOMATION_DIR}/"
fi

log "🔧 Claudio Commit Skin finished"
exit 0