#!/bin/bash

# Claudio Commit Skin Installer
# Auto-installs the 80/20 Solutions commit workflow automation

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKIN_VERSION="v1.0.0"

echo "🔧 Installing Claudio Commit Skin ${SKIN_VERSION}..."
echo ""

# Check if we're in a git repository
if [ ! -d ".git" ]; then
    echo "❌ Error: Not in a git repository"
    echo "   Please run this script from the root of your project repository"
    exit 1
fi

# Get current directory name for project detection
PROJECT_DIR=$(basename "$PWD")
echo "📁 Installing in project: ${PROJECT_DIR}"

# Check for existing hook and backup
if [ -f ".git/hooks/pre-commit" ]; then
    echo "⚠️  Existing pre-commit hook found, backing up..."
    mv ".git/hooks/pre-commit" ".git/hooks/pre-commit.backup.$(date +%s)"
fi

# Copy the main commit flow script
echo "📋 Installing commit flow script..."
cp "${SCRIPT_DIR}/commit-flow.sh" ".git/hooks/pre-commit"
chmod +x ".git/hooks/pre-commit"

# Copy configuration files  
echo "⚙️  Installing configuration..."
mkdir -p ".commit-skin"
cp "${SCRIPT_DIR}/config/project-config.json" ".commit-skin/"
cp "${SCRIPT_DIR}/config/version-rules.json" ".commit-skin/"

# Create PROJECT.md if it doesn't exist
if [ ! -f "PROJECT.md" ]; then
    echo "📄 Creating PROJECT.md from template..."
    curl -sSL "https://raw.githubusercontent.com/ecologicaleaving/sugitup/main/PROJECT_MD_TEMPLATE.md" > "PROJECT.md.template"
    
    # Customize template with current project info
    PROJECT_NAME=$(echo "${PROJECT_DIR}" | sed 's/-/ /g' | sed 's/\b\w/\u&/g')
    GITHUB_URL="https://github.com/ecologicaleaving/${PROJECT_DIR}"
    
    sed -e "s/\[Nome progetto pubblico\]/${PROJECT_NAME}/" \
        -e "s/\[v1.2.3 - semantic versioning\]/v1.0.0/" \
        -e "s/\[development|staging|production\]/development/" \
        -e "s|\[https://github.com/account/repo\]|${GITHUB_URL}|" \
        "PROJECT.md.template" > "PROJECT.md"
    
    rm "PROJECT.md.template"
    echo "   ✅ PROJECT.md created and customized"
fi

# Create releases directory
echo "📦 Setting up releases directory..."
mkdir -p "releases"
echo "# Release Artifacts" > "releases/README.md"
echo "" >> "releases/README.md"
echo "This directory contains built artifacts ready for deployment." >> "releases/README.md"
echo "Files here are auto-generated by the claudio-commit-skin." >> "releases/README.md"

# Add .gitignore rules if needed
if [ ! -f ".gitignore" ]; then
    echo "📄 Creating .gitignore..."
    touch ".gitignore"
fi

# Add commit-skin specific ignores if not present
grep -qxF ".commit-skin/cache/" ".gitignore" || echo ".commit-skin/cache/" >> ".gitignore"
grep -qxF "*.log" ".gitignore" || echo "*.log" >> ".gitignore"

# Test the installation
echo ""
echo "🧪 Testing installation..."

# Test PROJECT.md parsing
if [ -f "PROJECT.md" ]; then
    echo "   ✅ PROJECT.md found"
else
    echo "   ❌ PROJECT.md missing"
fi

# Test hook execution permissions
if [ -x ".git/hooks/pre-commit" ]; then
    echo "   ✅ Pre-commit hook executable"
else
    echo "   ❌ Pre-commit hook not executable"
fi

# Detect project type
PROJECT_TYPE="unknown"
if [ -f "pubspec.yaml" ]; then
    PROJECT_TYPE="flutter"
    echo "   📱 Flutter project detected"
elif [ -f "package.json" ]; then
    PROJECT_TYPE="nodejs"
    echo "   🌐 Node.js project detected"
elif [ -f "index.html" ]; then
    PROJECT_TYPE="static"
    echo "   📄 Static site detected"
fi

# Save project configuration
cat > ".commit-skin/project-config.json" << EOF
{
  "project_name": "${PROJECT_NAME}",
  "project_type": "${PROJECT_TYPE}",
  "skin_version": "${SKIN_VERSION}",
  "installed_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "github_url": "${GITHUB_URL}"
}
EOF

echo ""
echo "✅ Installation complete!"
echo ""
echo "🎯 Next steps:"
echo "   1. Make a test commit: git add . && git commit -m 'test: skin installation'"
echo "   2. The skin will automatically:"
echo "      - Update PROJECT.md with version and timestamp"
echo "      - Build the project if needed (Flutter APK, npm build, etc.)"
echo "      - Copy artifacts to releases/ directory" 
echo "      - Commit everything together"
echo ""
echo "📋 Commands:"
echo "   - Check skin status: cat .commit-skin/project-config.json"
echo "   - Uninstall: rm .git/hooks/pre-commit && rm -rf .commit-skin"
echo ""
echo "🔧 Configuration files:"
echo "   - .commit-skin/project-config.json (project settings)"
echo "   - .commit-skin/version-rules.json (version increment rules)"
echo ""
echo "Happy coding! 🚀"