#!/usr/bin/env bash
# install-kanban.sh — Install the Kanban automation caller workflow into a target repo
# Usage: ./scripts/install-kanban.sh /path/to/target-repo
#
# Creates a caller workflow in the target repo that invokes the reusable
# kanban-automation workflow from ecologicaleaving/workflow.

set -euo pipefail

show_help() {
  cat <<EOF
Usage: $(basename "$0") TARGET_REPO_PATH

Install the Kanban automation caller workflow into a target repository.

Arguments:
  TARGET_REPO_PATH    Path to the target repository root

Options:
  --help, -h          Show this help message

What it does:
  Creates .github/workflows/kanban-caller.yml in the target repo.
  This caller workflow triggers on PR events and invokes the reusable
  kanban-automation.yml from ecologicaleaving/workflow.
EOF
  exit 0
}

# --- Parse args ---
case "${1:-}" in
  --help|-h) show_help ;;
  "") echo "❌ Usage: $(basename "$0") TARGET_REPO_PATH" >&2; exit 1 ;;
esac

TARGET="$1"

if [[ ! -d "$TARGET" ]]; then
  echo "❌ Target directory not found: $TARGET" >&2
  exit 1
fi

DEST_DIR="$TARGET/.github/workflows"
mkdir -p "$DEST_DIR"

cat > "$DEST_DIR/kanban-caller.yml" <<'WORKFLOW'
# Auto-generated by install-kanban.sh from ecologicaleaving/workflow
# Calls the reusable kanban-automation workflow on PR events.

name: Kanban Automation

on:
  pull_request:
    types: [opened, closed]

jobs:
  kanban-on-pr-opened:
    if: github.event.action == 'opened'
    uses: ecologicaleaving/workflow/.github/workflows/kanban-automation.yml@master
    with:
      issue_number: ${{ github.event.pull_request.number }}
      event_type: pr_opened
    secrets: inherit

  kanban-on-pr-merged:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    uses: ecologicaleaving/workflow/.github/workflows/kanban-automation.yml@master
    with:
      issue_number: ${{ github.event.pull_request.number }}
      event_type: pr_merged
    secrets: inherit
WORKFLOW

echo "✅ Kanban caller workflow installed at $DEST_DIR/kanban-caller.yml"
